################################
POST http://localhost:3001/api/task
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGI1NmRjMTczOTM4MjFmMGUzY2RjZiIsImVtYWlsIjoiamlwc29ubXVyaWxsb0BnbWFpbC5jb20iLCJpYXQiOjE2MjgxMzMwOTh9.pdzXmLnAgqigxfRi8qy0yY5_3Y7bEsunKVwzcjcpUwk

{
    "content": "Hola soy segunda nota",
    "important": false
  }

################################
PUT http://localhost:3001/api/task/610b571317393821f0e3cdd3
content-type: application/json

{
    "content": "Hola soy holaa nota2",
    "important": true
  }